#!/bin/sh
#
# Activate Bluetooth for Variscite DART-6UL / VAR-SOM-MX7 / MX6-VAR-SOM
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.

# Load board-specific configuration settings
. /etc/bluetooth/variscite-bt.conf


# Enable BT via GPIO
enable_bt() {
  if [ ! -d /sys/class/gpio/gpio${BT_GPIO} ]; then
    echo ${BT_GPIO} >/sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio${BT_GPIO}/direction
  fi
  echo 0 > /sys/class/gpio/gpio${BT_GPIO}/value
  sleep 1
  echo 1 > /sys/class/gpio/gpio${BT_GPIO}/value
}


###########################
#  Execution starts here  #
###########################
for i in $(seq 1 5); do

  # Enable BT hardware
  enable_bt

  # Load BT firmware
  pidof hciattach >/dev/null && killall -9 hciattach
  hciattach -t 10 -s 115200 ${BT_TTY_DEV} texas 3000000 flow

  # Check that hci0 interface exists
  if hciconfig | grep -q hci0; then
    exit 0
  fi

done

exit 1
